/* summon_client.cpp

 Generated by phxrpc_pb2client from summon.proto

*/

#include "summon_client.h"

#include <cstdlib>
#include <memory>
#include <mutex>

#include "phxrpc/http.h"
#include "phxrpc/rpc.h"

#include "phxrpc_summon_stub.h"


using namespace std;


static phxrpc::ClientConfig global_summonclient_config_;
static phxrpc::ClientMonitorPtr global_summonclient_monitor_;


bool SummonClient::Init(const char *config_file) {
    return global_summonclient_config_.Read(config_file);
}

const char *SummonClient::GetPackageName() {
    const char *ret = global_summonclient_config_.GetPackageName();
    if (strlen(ret) == 0) {
        ret = "summon";
    }
    return ret;
}

SummonClient::SummonClient() {
    static mutex monitor_mutex;
    if (!global_summonclient_monitor_.get()) {
        monitor_mutex.lock();
        if (!global_summonclient_monitor_.get()) {
            global_summonclient_monitor_ = phxrpc::MonitorFactory::GetFactory()->
                    CreateClientMonitor(GetPackageName());
        }
        global_summonclient_config_.SetClientMonitor(global_summonclient_monitor_);
        monitor_mutex.unlock();
    }
}

SummonClient::~SummonClient() {
}

int SummonClient::PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp)
{
    const phxrpc::Endpoint_t *ep{global_summonclient_config_.GetRandom()};

    if (ep) {
        phxrpc::BlockTcpStream socket;
        bool open_ret{phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                global_summonclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                *(global_summonclient_monitor_.get()))};
        if (open_ret) {
            socket.SetTimeout(global_summonclient_config_.GetSocketTimeoutMS());
            phxrpc::HttpMessageHandlerFactory http_msg_factory;
            SummonStub stub(socket, *(global_summonclient_monitor_.get()), http_msg_factory);
            return stub.PHXEcho(req, resp);
        }

    }

    return -1;
}

int SummonClient::PHXBatchEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp)
{
    int ret{-1};
    size_t echo_server_count{2};
    uthread_begin;
    for (size_t i{0}; echo_server_count > i; ++i) {
        uthread_t [=, &uthread_s, &ret](void *) {
            const phxrpc::Endpoint_t *ep = global_summonclient_config_.GetByIndex(i);
            if (ep != nullptr) {
                phxrpc::UThreadTcpStream socket;
                if (phxrpc::PhxrpcTcpUtils::Open(&uthread_s, &socket, ep->ip, ep->port,
                    global_summonclient_config_.GetConnectTimeoutMS(), *(global_summonclient_monitor_.get()))) {
                    socket.SetTimeout(global_summonclient_config_.GetSocketTimeoutMS());
                    phxrpc::HttpMessageHandlerFactory http_msg_factory;
                    SummonStub stub(socket, *(global_summonclient_monitor_.get()), http_msg_factory);
                    int this_ret{stub.PHXEcho(req, resp)};
                    if (this_ret == 0) {
                        ret = this_ret;
                        uthread_s.Close();
                    }
                }
            }
        };
    }
    uthread_end;
    return ret;
}

int SummonClient::Summon(const summon::SummonRequest &req, summon::SummonResult *resp)
{
    const phxrpc::Endpoint_t *ep{global_summonclient_config_.GetRandom()};

    if (ep) {
        phxrpc::BlockTcpStream socket;
        bool open_ret{phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                global_summonclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                *(global_summonclient_monitor_.get()))};
        if (open_ret) {
            socket.SetTimeout(global_summonclient_config_.GetSocketTimeoutMS());
            phxrpc::HttpMessageHandlerFactory http_msg_factory;
            SummonStub stub(socket, *(global_summonclient_monitor_.get()), http_msg_factory);
            return stub.Summon(req, resp);
        }

    }

    return -1;
}

