/* summon_client.h

 Generated by phxrpc_pb2client from summon.proto

*/

#pragma once

#include "../summon.pb.h"
#include "phxrpc/rpc.h"


class SummonClient {
  public:
    static bool Init(const char *config_file);

    static const char *GetPackageName();

    SummonClient();
    virtual ~SummonClient();

    int PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp);
    int PHXBatchEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp);
    int Summon(const summon::SummonRequest &req, summon::SummonResult *resp);
};

