/* phxrpc_summon_dispatcher.h

 Generated by phxrpc_pb2service from summon.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_summon_dispatcher.h"

#include <errno.h>

#include "phxrpc/http.h"
#include "phxrpc/file.h"

#include "../summon.pb.h"
#include "phxrpc_summon_service.h"


SummonDispatcher::SummonDispatcher(SummonService &service, phxrpc::DispatcherArgs_t *dispatcher_args)
        : service_(service), dispatcher_args_(dispatcher_args) {
}

SummonDispatcher::~SummonDispatcher() {
}

const phxrpc::BaseDispatcher<SummonDispatcher>::URIFuncMap &SummonDispatcher::GetURIFuncMap() {
    static phxrpc::BaseDispatcher<SummonDispatcher>::URIFuncMap uri_func_map = {
        {"/summon/PHXEcho", &SummonDispatcher::PHXEcho},
        {"/summon/Summon", &SummonDispatcher::Summon}};
    return uri_func_map;
}

int SummonDispatcher::PHXEcho(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp) {
    dispatcher_args_->server_monitor->SvrCall(-1, "PHXEcho", 1);

    int ret{-1};

    google::protobuf::StringValue req_pb;
    google::protobuf::StringValue resp_pb;

    // unpack request
    {
        ret = req.ToPb(&req_pb);
        if (0 != ret) {
            phxrpc::log(LOG_ERR, "ToPb err %d", ret);

            return -EINVAL;
        }
    }

    // logic process
    {
        if (0 == ret) {
            ret = service_.PHXEcho(req_pb, &resp_pb);
        }
    }

    // pack response
    {
        if (0 != resp->FromPb(resp_pb)) {
            phxrpc::log(LOG_ERR, "FromPb err %d", ret);

            return -ENOMEM;
        }
    }

    phxrpc::log(LOG_DEBUG, "RETN: PHXEcho = %d", ret);

    return ret;
}

int SummonDispatcher::Summon(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp) {
    dispatcher_args_->server_monitor->SvrCall(1, "Summon", 1);

    int ret{-1};

    summon::SummonRequest req_pb;
    summon::SummonResult resp_pb;

    // unpack request
    {
        ret = req.ToPb(&req_pb);
        if (0 != ret) {
            phxrpc::log(LOG_ERR, "ToPb err %d", ret);

            return -EINVAL;
        }
    }

    // logic process
    {
        if (0 == ret) {
            ret = service_.Summon(req_pb, &resp_pb);
        }
    }

    // pack response
    {
        if (0 != resp->FromPb(resp_pb)) {
            phxrpc::log(LOG_ERR, "FromPb err %d", ret);

            return -ENOMEM;
        }
    }

    phxrpc::log(LOG_DEBUG, "RETN: Summon = %d", ret);

    return ret;
}

