/* phxrpc_summon_service.cpp

 Generated by phxrpc_pb2service from summon.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_summon_service.h"

#include "../summon.pb.h"
#include "phxrpc/file.h"


SummonService::SummonService() {
}

SummonService::~SummonService() {
}

int SummonService::PHXEcho(const google::protobuf::StringValue &/* req */, google::protobuf::StringValue */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: PHXEcho unimplemented");
    return -1;
}

int SummonService::Summon(const summon::SummonRequest &/* req */, summon::SummonResult */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: Summon unimplemented");
    return -1;
}

