/* phxrpc_summon_service.h

 Generated by phxrpc_pb2service from summon.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "../summon.pb.h"


class SummonService {
  public:
    SummonService();
    virtual ~SummonService();

    virtual int PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp);
    virtual int Summon(const summon::SummonRequest &req, summon::SummonResult *resp);
};

