/* phxrpc_summon_dispatcher.h

 Generated by phxrpc_pb2service from summon.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "phxrpc/rpc.h"


class SummonService;

class SummonDispatcher {
  public:
    static const phxrpc::BaseDispatcher<SummonDispatcher>::URIFuncMap &GetURIFuncMap();

    SummonDispatcher(SummonService &service, phxrpc::DispatcherArgs_t *dispatcher_args);

    virtual ~SummonDispatcher();

    int PHXEcho(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp);
    int Summon(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp);

  private:
    SummonService &service_;
    phxrpc::DispatcherArgs_t *dispatcher_args_;
};

