/* summon_service_impl.cpp

 Generated by phxrpc_pb2service from summon.proto

*/

#include "summon_service_impl.h"

#include "phxrpc/file.h"

#include "summon_server_config.h"
#include "../summon.pb.h"


using namespace std;


SummonServiceImpl::SummonServiceImpl(ServiceArgs_t &app_args) : args_(app_args) {
}

SummonServiceImpl::~SummonServiceImpl() {
}

int SummonServiceImpl::PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) {
    resp->set_value(req.value());
    return 0;
}

summon::RoleType types[] = {summon::SSR, summon::SR, summon::R};
int SummonServiceImpl::Summon(const summon::SummonRequest &req, summon::SummonResult *resp) {

	int number = req.number();
	resp->set_id(req.id());
	for (int i = 0; i < number; ++i)
	{
		resp->add_role_type(types[i % 3]);
	}

	phxrpc::log(LOG_INFO, "[id: %s] summon result\n%s\n", req.id().c_str(),
		resp->Utf8DebugString().c_str());

	return 0;
}

