/* summon_server_config.cpp

 Generated by phxrpc_pb2server from summon.proto

*/

#include "summon_server_config.h"

#include "../summon.pb.h"


SummonServerConfig::SummonServerConfig() {
}

SummonServerConfig::~SummonServerConfig() {
}

bool SummonServerConfig::Read(const char *config_file) {
    bool ret{ep_server_config_.Read(config_file)};

    if (0 == strlen(ep_server_config_.GetPackageName())) {
        ep_server_config_.SetPackageName(
                summon::SummonRequest::default_instance().GetDescriptor()->file()->package().c_str());
    }

    return ret;
}

phxrpc::HshaServerConfig &SummonServerConfig::GetHshaServerConfig() {
    return ep_server_config_;
}

