/* summon_server_config.h

 Generated by phxrpc_pb2server from summon.proto

*/

#pragma once

#include "phxrpc/rpc.h"


class SummonServerConfig {
  public:
    SummonServerConfig();

    virtual ~SummonServerConfig();

    bool Read(const char *config_file);

    phxrpc::HshaServerConfig &GetHshaServerConfig();

  private:
    phxrpc::HshaServerConfig ep_server_config_;
};

