/* summon_service_impl.h

 Generated by phxrpc_pb2service from summon.proto

*/

#pragma once

#include "../summon.pb.h"
#include "phxrpc_summon_service.h"


class SummonServerConfig;

typedef struct tagServiceArgs {
    SummonServerConfig *config;
    // you can add other arguments here and initiate in main().
} ServiceArgs_t;

class SummonServiceImpl : public SummonService {
  public:
    SummonServiceImpl(ServiceArgs_t &app_args);
    virtual ~SummonServiceImpl() override;

    virtual int PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) override;
    virtual int Summon(const summon::SummonRequest &req, summon::SummonResult *resp) override;

  private:
    ServiceArgs_t &args_;
};

